### PR TITLE
Return a promise on a buffer passed in + update gruntfile

### PR DESCRIPTION
**Pull request by sainsb**
When passing in a buffer, a promise wasn't being returned...not sure exactly how you want to implement this...but this got me over my hurdle....also...outdated gruntfile.
more PRs coming soon.

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
Iv been moving away from grunt and towards npm scripts, see the recent
update to shapefile-js

**Comment by calvinmetcalf** [comment]
(otherwise your pull looks good so far)

**Comment by sainsb** [comment]
Hmmm....ok. After creating the pull request I realized that the Browserify upgrade in the gruntfile somehow destroyed the fgdb namespace and so...can't ... use... will explore the npm scripts approach...seems simpler. I guess...

**Comment by calvinmetcalf** [comment]
so I'm merging this in and looking through the api, it was set up to only be async if you gave it a path, and be sync if you gave it data, obviously this is a little confusing so this will probably be a major version change, also don't worry about grunt I can fix the build system (and any additional pulls are about to be bit rotted due to a massive cleanup of the formatting)

**Pull request merged**
